apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkpoints-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "" 
  gcePersistentDisk:
    pdName: pvc-af78cece-bada-421c-bddf-6c11b304009f
    fsType: ext4