apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: elastic-train
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            app: pytorch-worker
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: pytorch-worker
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: pytorch
              image: us-central1-docker.pkg.dev/apt-passage-465114-b4/reranker-training-repo/reranker-training
              command: ["torchrun"]
              args:
                - "--nnodes=1:1"
                - "--nproc_per_node"
                - "1"
                - "--rdzv_backend=c10d"
                - "--rdzv_endpoint=rdzv-service:29400"
                - "-m"
                - "FlagEmbedding.finetune.reranker.encoder_only.base"
                - "--model_name_or_path"
                - "BAAI/bge-reranker-large"
                - "--train_data"
                - "./reranker_case_hold_dataset.jsonl"
                - "--train_group_size"
                - "3"
                - "--query_max_len"
                - "256"
                - "--passage_max_len"
                - "256"
                - "--pad_to_multiple_of"
                - "8"
                - "--knowledge_distillation"
                - "False"
                - "--output_dir"
                - "/mnt/checkpoints"
                - "--resume_from_checkpoint"
                - "/mnt/checkpoints"
                - "--learning_rate"
                - "2e-5"
                - "--fp16"
                - "--num_train_epochs"
                - "2"
                - "--per_device_train_batch_size"
                - "6"
                - "--gradient_accumulation_steps"
                - "1"
                - "--dataloader_drop_last"
                - "True"
                - "--warmup_ratio"
                - "0.1"
                - "--weight_decay"
                - "0.01"
                - "--logging_steps"
                - "200"
                - "--deepspeed"
                - "ds_stage0.json"
                - "--save_steps"
                - "250"
                - "--save_total_limit"
                - "5"
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - name: checkpoints
                  mountPath: /mnt/checkpoints
          volumes:
            - name: checkpoints
              persistentVolumeClaim:
                claimName: checkpoints-pvc