apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: elastic-train
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: pytorch-worker
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: pytorch
              image: us-central1-docker.pkg.dev/apt-passage-465114-b4/reranker-training-repo/reranker-training
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - name: checkpoints
                  mountPath: /mnt/checkpoints
          volumes:
            - name: checkpoints
              persistentVolumeClaim:
                claimName: checkpoints-pvc
          labels:
            app: pytorch-worker